### ISSUE TITLE
Experience boxes clipping text

### ISSUE THREAD

**Issue by sudface** [gatlace/website#2]
On screens less than 1920px wide, text at the bottom of the language experience boxes is cut off. Attached below is a screenshot. 

![image](https://user-images.githubusercontent.com/31204774/177258479-99e298f7-bb63-436c-94f4-022279da78a2.png)

For reference, my screen is 1600px wide.

**Comment by ziidonato** [comment]
Thank you for letting me know.

I made the tiles scroll when they overflow, not a perfect solution but the results seem ok.
